#!/bin/bash

# Script de déploiement pour la migration corrigée device_model_services
# Résout les problèmes de types entre les tables

echo "🚀 Déploiement de la migration corrigée device_model_services"
echo ""

# Vérifier que le fichier SQL existe
if [ ! -f "create_device_model_services_corrected.sql" ]; then
    echo "❌ Erreur: Le fichier create_device_model_services_corrected.sql n'existe pas"
    exit 1
fi

echo "📋 Instructions pour appliquer la migration corrigée:"
echo ""
echo "1. Connectez-vous à votre dashboard Supabase:"
echo "   https://supabase.com/dashboard"
echo ""
echo "2. Sélectionnez votre projet"
echo ""
echo "3. Allez dans l'éditeur SQL (SQL Editor)"
echo ""
echo "4. Copiez le contenu du fichier 'create_device_model_services_corrected.sql'"
echo ""
echo "5. Collez-le dans l'éditeur SQL"
echo ""
echo "6. Cliquez sur 'Run' pour exécuter le script"
echo ""
echo "7. Vérifiez que vous voyez les messages de succès:"
echo "   ✅ Table device_model_services existe"
echo "   ✅ Vue device_model_services_detailed existe"
echo "   ✅ Politiques RLS configurées"
echo ""
echo "✅ Cette version corrige les problèmes de types:"
echo "   - Utilise TEXT pour brand_id et category_id (compatible avec device_models)"
echo "   - Utilise ::text pour les jointures avec device_brands et device_categories"
echo "   - Évite les erreurs de type UUID vs TEXT"
echo ""
echo "📁 Fichier SQL à utiliser: create_device_model_services_corrected.sql"
echo ""
echo "🔧 Ce script fait tout automatiquement:"
echo "   - Diagnostique les types existants"
echo "   - Supprime l'ancienne table si elle existe"
echo "   - Crée la table avec les bons types"
echo "   - Configure tous les index et contraintes"
echo "   - Crée la vue avec conversion de types"
echo "   - Configure les politiques RLS"
echo "   - Crée les fonctions RPC"
echo "   - Crée le trigger updated_at"
echo "   - Vérifie que tout fonctionne"
echo ""
echo "⚠️  Prérequis: Les tables suivantes doivent exister:"
echo "   - device_models (avec brand_id et category_id de type TEXT)"
echo "   - services"
echo "   - device_brands (avec id de type UUID)"
echo "   - device_categories (avec id de type UUID)"
echo "   - workshops (optionnel)"
echo ""
echo "🎯 Une fois le script exécuté, l'application devrait fonctionner sans erreur 404"
echo ""
echo "🧪 Pour tester après l'exécution:"
echo "   1. Rechargez votre application"
echo "   2. Essayez de créer une association service-modèle"
echo "   3. Vérifiez qu'il n'y a plus d'erreur 404 dans la console"
echo ""
echo "🔍 Si vous voulez diagnostiquer les types avant:"
echo "   Exécutez d'abord 'diagnose_table_types.sql' pour voir les types existants"
