databaseType = "PostgreSql"
id = "b9551643-44fb-441a-abdc-3eb223b32b9d"
name = "Atelier Gestion"

[flyway]
defaultSchema = "public"
locations = [ "filesystem:migrations" ]
baselineOnMigrate = true
baselineVersion = "0"
validateMigrationNaming = true

[flywayDesktop]
developmentEnvironment = "production"
shadowEnvironment = "shadow"

[environments.development]
url = "jdbc:postgresql://db.olrihggkxyksuofkesnk.supabase.co:5432/postgres"
user = "postgres"
password = "ubazddRhIBL17UQr"
schemas = [ "public" ]

[environments.production]
url = "jdbc:postgresql://db.wlqyrmntfxwdvkzzsujv.supabase.co:5432/postgres"
user = "postgres"
password = "EGQUN6paP21OlNUu"
schemas = [ "public" ]
